// <auto-generated />
using System;
using System.Collections.Generic;
using BankTransferApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankTransferApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423102740_CreateUserTable")]
    partial class CreateUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankTransferApp.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "BankTransferApp.Domain.Entities.UserEntity.Address#AddressValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("char")
                                .HasColumnName("City");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("char")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("char")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("char")
                                .HasColumnName("ZipCode");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cellphone", "BankTransferApp.Domain.Entities.UserEntity.Cellphone#TelephoneValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AreaCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("char")
                                .HasColumnName("CellphoneAreaCode");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("char")
                                .HasColumnName("CellphoneNumber");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CpfDocument", "BankTransferApp.Domain.Entities.UserEntity.CpfDocument#CpfValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("char")
                                .HasColumnName("Cpf");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "HomePhone", "BankTransferApp.Domain.Entities.UserEntity.HomePhone#TelephoneValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AreaCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("char")
                                .HasColumnName("HomePhoneAreaCode");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("char")
                                .HasColumnName("HomePhoneNumber");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "BankTransferApp.Domain.Entities.UserEntity.Name#PersonNameValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("char")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("char")
                                .HasColumnName("LastName");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Password", "BankTransferApp.Domain.Entities.UserEntity.Password#PasswordValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("Password");
                        });

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
